[theme]
name = "gruvbox-dark"

[icons]
name = "awesome"


[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
full_threshold = 85

[[block]]
block = "temperature"
format = "{min}{average}{max}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "memory"
format_mem = "{mem_used} ({mem_used_percents})"
display_type = "memory"
clickable = false
icons = true
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "sound"
step_width = 5
max_vol = 100

[[block]]
block = "time"
format = "%a %m/%d %r"
timezone = "US/Eastern"
interval = 1
locale = "en_US"
