[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome4"

[[block]]
block = "battery"
interval = 10
format = "$icon $percentage $time"
full_threshold = 85

[[block]]
block = "temperature"
format = "$icon $min $average $max"

[[block]]
block = "cpu"
interval = 1
format = "$icon $barchart $utilization $frequency"

[[block]]
block = "memory"
format = "$icon $mem_used ($mem_used_percents)"
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "sound"
step_width = 5
max_vol = 100

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%a %m/%d %T')"
timezone = "US/Eastern"
interval = 1
