[theme]
name = "gruvbox-dark"

[icons]
name = "awesome"


[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "memory"
format_mem = "{mem_used}({mem_used_percents})"
display_type = "memory"
icons = true
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
format = "%a %m/%d %r"
timezone = "US/Eastern"
interval = 1
locale = "en_US"
